### PR TITLE
[FIX] address lint error messages

### LINKED ISSUE #272: Linting issues
There are a few linter warnings in the console. It would be good if they could be cleaned up.
```
3:29:26 PM: ./pages/404.tsx
3:29:26 PM: 11:10  Warning: 't' is assigned a value but never used.  @typescript-eslint/no-unused-vars
3:29:26 PM: 33:25  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: ./pages/[content].tsx
3:29:26 PM: 38:10  Warning: 't' is assigned a value but never used.  @typescript-eslint/no-unused-vars
3:29:26 PM: 74:18  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: 95:18  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: 96:25  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: ./pages/about.tsx
3:29:26 PM: 15:10  Warning: 't' is assigned a value but never used.  @typescript-eslint/no-unused-vars
3:29:26 PM: 41:25  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: ./pages/index.tsx
3:29:26 PM: 35:25  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
3:29:26 PM: ./components/CodeBlock/CodeBlock.tsx
3:29:26 PM: 4:6  Warning: Type Alias name `TCodeLanguage` must match one of the following formats: StrictPascalCase  @typescript-eslint/naming-convention
3:29:26 PM: ./components/PageUpdated/PageUpdated.tsx
3:29:26 PM: 1:8  Warning: 'styles' is defined but never used.  @typescript-eslint/no-unused-vars
3:29:26 PM: ./components/ThemeSwitcher/ThemeSwitcher.tsx
3:29:26 PM: 49:5  Warning: React Hook useEffect has a missing dependency: 'handleThemeSwitcherKB'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```

### PR DESCRIPTION
**Pull request by at-the-vr**
## Describe your changes
This PR Includes lint error messages fixes
- Forbidden non-null assertion: [referred documentation](https://typescript-eslint.io/rules/no-non-null-assertion/), check the correct example
- 't' is assigned a value but never used: [referred documentation](https://eslint.org/docs/latest/use/configure/rules#using-configuration-comments-1) + Intellisense Suggestion ( I was receiving about 4 console logs each time for different content being mounted)
- Type Alias name `TCodeLanguage` must match one of the following formats StrictPascalcase: small typo fix
- 'styles' is defined but never used: styles is being referred from `PageUpdated.module.css` which is currently empty, so i removed its declaration for time being
- React Hook useEffect has a missing dependency `handleThemeSwitcherKB`: removing the array works normally as far as I have tried but it can also work fine with 
```js
useEffect(() => {
  document.addEventListener("keyup", handleThemeSwitcherKB);

  return () => document.removeEventListener("keyup", handleThemeSwitcherKB);
}, [handleThemeSwitcherKB]);
```
I did not used React Dev Tools to check the value of handleThemeSwitcherKB, but let me know if this needs to change

## Link to issue

Closes #272 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [x] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.

### CODE REVIEW

File: components/CodeBlock/CodeBlock.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { Prism as SyntaxHighlighter } from "react-syntax-highlighter"
 import { dracula } from "react-syntax-highlighter/dist/cjs/styles/prism"
 
-type TCodeLanguage =
+type TcodeLanguage =
```
Comment (EmmaDawsonDev) [inline components/CodeBlock/CodeBlock.tsx:4]: Although this technically solves the issue I don't think this is a good pattern to follow. It is supposed to be named `TCodeLanguage`. I think we need to update the config file instead to allow types to follow this naming convention.

```
{
"selector": "type",
"format": ["PascalCase"]
},
```

File: components/ThemeSwitcher/ThemeSwitcher.tsx [hunk 2]
```diff
@@ -46,7 +46,7 @@ export const ThemeSwitcher = () => {
 		document.addEventListener("keyup", handleThemeSwitcherKB)
 
 		return () => document.removeEventListener("keyup", handleThemeSwitcherKB)
-	}, [])
+	})
```
Comment (EmmaDawsonDev) [inline components/ThemeSwitcher/ThemeSwitcher.tsx:49]: The array is there to make sure the event listeners are only rendered when the component mounts. By removing the array the useEffect runs every time anything rerenders which is not the behaviour wanted. Either an eslint comment should be used to ignore the empty array or the function can be added to the array and wrapped in a useCallback function so it doesn't get recreated on every render.

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Thanks for your help. This is looking good, just a couple of things need changing before it can be merged.

File: components/CodeBlock/CodeBlock.tsx (hunk 1 above)
Comment (at-the-vr) [reply components/CodeBlock/CodeBlock.tsx:4]: I see Cristian has already specified the format for `typeLikes` in eslintrc.json file, how about I update the convention to also include PascalCase like this
```js
{
        "selector": "typeLike",
        "format": ["StrictPascalCase", "PascalCase"]				
},
```
It does solves the issue while keeping `TCodeLanguage` as it is

File: components/ThemeSwitcher/ThemeSwitcher.tsx (hunk 2 above)
Comment (at-the-vr) [reply components/ThemeSwitcher/ThemeSwitcher.tsx:49]: I have to read more for this one, will let ya know soon

File: components/CodeBlock/CodeBlock.tsx (hunk 1 above)
Comment (EmmaDawsonDev) [reply components/CodeBlock/CodeBlock.tsx:4]: Sure!

File: components/ThemeSwitcher/ThemeSwitcher.tsx (hunk 2 above)
Comment (at-the-vr) [reply components/ThemeSwitcher/ThemeSwitcher.tsx]: took the eslint disable way

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good! Thanks for your help :)
